CREATE TABLE TBL_BILLING_LOG(
log_date TIMESTAMP,
ProtocolNum STRING,
feeType STRING,
chargepolicy STRING,
SDKVersion STRING,
cid STRING,
chid STRING,
pakid STRING,
consumeid STRING,
IMSI STRING,
cpparam STRING,
IMEI STRING,
sessionid STRING,
msisdn STRING,
ms STRING,
sbf STRING,
packer STRING,
SDKSessionID STRING,
apkstatus STRING,
deposits STRING,
cpid STRING,
vcode STRING,
LoginUserID STRING,
appid STRING,
billingcount STRING,
TS STRING,
billinginterval STRING,
IMEIStatus STRING,
IMSIStatus STRING,
SDKStatus STRING,
SESSIONTS STRING,
SessionInterval STRING,
SessionIMEI STRING,
SessionIMSI STRING,
dev_mac STRING,
soversion STRING,
flag STRING,
returnvalue STRING,
iSession STRING,
secureType STRING,
sms_http STRING,
reserved1 STRING,
reserved2 STRING,
reserved3 STRING,
reserved4 STRING,
reserved5 STRING
)row format delimited fields terminated by ',' STORED AS INPUTFORMAT 'com.yemast.sla.common.extension.logprocess.BillingLogInputFormat' OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';


load data local inpath '/home/hadoop/billing' into table TBL_BILLING_LOG;